# docker-compose.yml

version: '3.8'

services:
  # 1. The Redis Cache Service
  redis:
    image: "redis:alpine"
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 2. Your FastAPI Application Service
  app:
    container_name: query-app
    # Build the image from the Dockerfile in the current directory
    build: .
    ports:
      - "8000:8000"
    # Pass the API key from your local .env file into the container
    env_file:
      - .env
    # This makes the 'redis' service available to your app at the hostname 'redis'
    depends_on:
      - redis

volumes:
  redis_data: